# Generated by Django 6.0.2 on 2026-03-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_remove_expense_category_remove_wallet_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(default='Outros', max_length=100),
        ),
    ]
