# Generated by Django 6.0.3 on 2026-03-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='dividend_per_share',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='investment',
            name='payment_frequency',
            field=models.CharField(default='Nenhum', max_length=50),
        ),
        migrations.AddField(
            model_name='investment',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=15),
        ),
    ]
